# Generated by Django 4.0.1 on 2022-02-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_email_confirmed_user_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_secret',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
