# Generated by Django 4.0.1 on 2022-03-06 12:17

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_alter_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='country',
            field=django_countries.fields.CountryField(default='KR', max_length=2),
        ),
    ]
