# Generated by Django 4.0.1 on 2022-02-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_alter_photo_file'),
        ('lists', '0002_remove_list_room_list_room_alter_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='room',
            field=models.ManyToManyField(blank=True, related_name='lists', to='rooms.Room'),
        ),
    ]
